### ISSUE TITLE
make mnemonic server based (secret)

### ISSUE THREAD

**Issue by kaisbaccour** [noislabs/pingpong#24]

**Comment by webmaster128** [comment]
Server based means environment variable?

**Comment by kaisbaccour** [comment]
One way to do it is env variable. could also be a file

**Comment by webmaster128** [comment]
But we already have the config file. Each instance could and should have its own copy of that file.

**Comment by kaisbaccour** [comment]
well some parts of the file are better handled centrally in code while others are better sever based
